# Generated by Django 4.2 on 2023-05-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logos',
            options={'verbose_name': 'logo', 'verbose_name_plural': 'logolar'},
        ),
    ]
