# Generated by Django 4.2 on 2023-05-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_logos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_lastname', models.CharField(max_length=200, verbose_name='Bergidaryň ady')),
                ('birthday', models.DateField(verbose_name='Doglan senesi:')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Telefon belgisi 1:')),
                ('phone_number2', models.CharField(max_length=12, verbose_name='Telefon belgisi 2:')),
                ('address', models.CharField(max_length=200, verbose_name='Öý salgysy:')),
                ('document_scan', models.FileField(blank=True, null=True, upload_to='file/<django.db.models.fields.CharField>', verbose_name='Passport nusgasy')),
                ('job_status', models.CharField(max_length=100, verbose_name='Işleýän ýeri:')),
            ],
            options={
                'verbose_name': 'Bergidar',
                'verbose_name_plural': 'Bergidarlar',
            },
        ),
    ]
