# Generated by Django 4.2 on 2023-05-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_mustpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mustpay',
            name='name_and_lastname',
            field=models.CharField(max_length=200, verbose_name='Bergidaryň ady we familiýasy:'),
        ),
        migrations.AlterField(
            model_name='mustpay',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon belgisi 2:'),
        ),
    ]
