# Generated by Django 4.2 on 2023-05-12 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_mustpay_document_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_lastname', models.CharField(max_length=200, unique=True, verbose_name='Algydaryň ady we familiýasy:')),
                ('birthday', models.DateField(verbose_name='Doglan senesi:')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Telefon belgisi:')),
                ('address', models.CharField(max_length=200, verbose_name='Öý salgysy:')),
                ('document_scan', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Passport nusgasy:')),
            ],
            options={
                'verbose_name': 'Algydar',
                'verbose_name_plural': 'Algydarlar',
            },
        ),
        migrations.AddField(
            model_name='mustpay',
            name='opened_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mustpay',
            name='document_scan',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Passport nusgasy:'),
        ),
    ]
