# Generated by Django 4.2 on 2023-05-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_mustpay_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='birthday',
            field=models.DateField(verbose_name='oglan senesi:'),
        ),
        migrations.CreateModel(
            name='RecipientChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_lastname', models.CharField(max_length=200, verbose_name='Çaganyň ady we Familiýasy:')),
                ('birthday', models.DateField(verbose_name='Doglan senesi:')),
                ('document_scan', models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Şahadatnama nusgasy')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='report.recipient', to_field='name_and_lastname', verbose_name='Algydar')),
            ],
            options={
                'verbose_name': 'Algydaryň çagasy',
                'verbose_name_plural': 'Algydarlaryň çagalary',
            },
        ),
    ]
