# Generated by Django 4.2 on 2023-05-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_recipient_birthday_recipientchild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mustpay',
            name='opened_date',
        ),
        migrations.RemoveField(
            model_name='mustpay',
            name='recipient',
        ),
    ]
