# Generated by Django 4.2 on 2023-05-16 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0015_alter_alimony_must_pay_alter_alimony_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='recipient_adder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin:'),
        ),
    ]
