# Generated by Django 4.2 on 2023-05-16 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0016_recipient_recipient_adder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='recipient_adder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Admin:'),
        ),
    ]
