# Generated by Django 4.2 on 2023-05-18 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_recipientchild_child_adder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mustpayreceipt',
            name='must_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='report.mustpay', to_field='name_and_lastname', verbose_name='Bergidar:'),
        ),
    ]
