# Generated by Django 4.2 on 2023-05-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_alter_mustpayreceipt_options_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Bolum', 'verbose_name_plural': 'Bolumler'},
        ),
        migrations.AlterField(
            model_name='alimony',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimonies', to='report.category', verbose_name='Bölum:'),
        ),
    ]
