# Generated by Django 4.2 on 2023-05-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimony',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimonies', to='report.category', to_field='name', verbose_name='Bölum:'),
        ),
    ]
