# Generated by Django 4.2 on 2023-05-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_alter_alimony_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimony',
            old_name='category',
            new_name='Category',
        ),
    ]
