# Generated by Django 4.2 on 2023-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_rename_category_alimony_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimony',
            name='began_paying',
            field=models.DateField(verbose_name='Alimenti tölän wagty:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ady:'),
        ),
    ]
