# Generated by Django 4.2 on 2023-05-26 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0025_alter_alimony_began_paying_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mustpay',
            name='mustpay_adder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Admin:'),
        ),
        migrations.AlterField(
            model_name='alimony',
            name='executor_date',
            field=models.DateTimeField(verbose_name='Önumçiligiň senesi:'),
        ),
        migrations.AlterField(
            model_name='alimony',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Admin:'),
        ),
    ]
