# Generated by Django 4.2 on 2023-05-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_alter_alimony_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mustpayreceipt',
            name='full_assessment',
        ),
        migrations.AlterField(
            model_name='mustpayreceipt',
            name='payment_date',
            field=models.DateField(verbose_name='Alimentiň tölenen senesi:'),
        ),
    ]
