# Generated by Django 4.2 on 2023-05-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_remove_mustpayreceipt_full_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimony',
            name='must_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimonies', to='report.mustpay', to_field='name_and_lastname', verbose_name='Bergidaryň ady we familiýasy:'),
        ),
        migrations.AlterField(
            model_name='alimony',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimonies', to='report.recipient', to_field='name_and_lastname', verbose_name='Algydaryn ady we familiyasy:'),
        ),
    ]
