# Generated by Django 4.1.6 on 2023-06-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0030_alter_alimony_executor_date_alter_alimony_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimony',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Işiň döredilen senesi:'),
        ),
    ]
