# Generated by Django 4.1.6 on 2023-06-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0031_alter_alimony_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimony',
            name='must_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimonies', to='report.mustpay', verbose_name='Bergidaryň ady we familiýasy:'),
        ),
    ]
