# Generated by Django 4.1.6 on 2023-06-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0033_alter_alimony_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimony',
            name='must_pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimonies', to='report.mustpay', to_field='name_and_lastname', verbose_name='Bergidaryň ady we familiýasy:'),
        ),
        migrations.AlterField(
            model_name='alimony',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimonies', to='report.recipient', to_field='name_and_lastname', verbose_name='Algydaryň ady we familiyasy:'),
        ),
    ]
